//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiLatinAmericaJourneys.ws_SendGridEmail {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autenticacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Autenticacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebApiLatinAmericaJourneys.ws_SendGridEmail.TipoWeb InWebIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.TipoWeb InWebId {
            get {
                return this.InWebIdField;
            }
            set {
                if ((this.InWebIdField.Equals(value) != true)) {
                    this.InWebIdField = value;
                    this.RaisePropertyChanged("InWebId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StUsuario {
            get {
                return this.StUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.StUsuarioField, value) != true)) {
                    this.StUsuarioField = value;
                    this.RaisePropertyChanged("StUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StClave {
            get {
                return this.StClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.StClaveField, value) != true)) {
                    this.StClaveField = value;
                    this.RaisePropertyChanged("StClave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoWeb", Namespace="http://tempuri.org/")]
    public enum TipoWeb : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mozart = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Correo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Correo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinatariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoTextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiLatinAmericaJourneys.ws_SendGridEmail.Adjunto[] AdjuntosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreEmisor {
            get {
                return this.NombreEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmisorField, value) != true)) {
                    this.NombreEmisorField = value;
                    this.RaisePropertyChanged("NombreEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CorreoEmisor {
            get {
                return this.CorreoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEmisorField, value) != true)) {
                    this.CorreoEmisorField = value;
                    this.RaisePropertyChanged("CorreoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Destinatarios {
            get {
                return this.DestinatariosField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatariosField, value) != true)) {
                    this.DestinatariosField = value;
                    this.RaisePropertyChanged("Destinatarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuerpoTexto {
            get {
                return this.CuerpoTextoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoTextoField, value) != true)) {
                    this.CuerpoTextoField = value;
                    this.RaisePropertyChanged("CuerpoTexto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CuerpoHtml {
            get {
                return this.CuerpoHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoHtmlField, value) != true)) {
                    this.CuerpoHtmlField = value;
                    this.RaisePropertyChanged("CuerpoHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.Adjunto[] Adjuntos {
            get {
                return this.AdjuntosField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjuntosField, value) != true)) {
                    this.AdjuntosField = value;
                    this.RaisePropertyChanged("Adjuntos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adjunto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Adjunto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ArchivoBytes {
            get {
                return this.ArchivoBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoBytesField, value) != true)) {
                    this.ArchivoBytesField = value;
                    this.RaisePropertyChanged("ArchivoBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebApiLatinAmericaJourneys.ws_SendGridEmail.TipoRespuesta TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtroValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.TipoRespuesta Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OtroValor {
            get {
                return this.OtroValorField;
            }
            set {
                if ((object.ReferenceEquals(this.OtroValorField, value) != true)) {
                    this.OtroValorField = value;
                    this.RaisePropertyChanged("OtroValor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRespuesta", Namespace="http://tempuri.org/")]
    public enum TipoRespuesta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exito = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alerta = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws_SendGridEmail.wsMailsSoap")]
    public interface wsMailsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento credenciales del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreo", ReplyAction="*")]
        WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponse EnviarCorreo(WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponse> EnviarCorreoAsync(WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreo", Namespace="http://tempuri.org/", Order=0)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequestBody Body;
        
        public EnviarCorreoRequest() {
        }
        
        public EnviarCorreoRequest(WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.Autenticacion credenciales;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.Correo informacion;
        
        public EnviarCorreoRequestBody() {
        }
        
        public EnviarCorreoRequestBody(WebApiLatinAmericaJourneys.ws_SendGridEmail.Autenticacion credenciales, WebApiLatinAmericaJourneys.ws_SendGridEmail.Correo informacion) {
            this.credenciales = credenciales;
            this.informacion = informacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponseBody Body;
        
        public EnviarCorreoResponse() {
        }
        
        public EnviarCorreoResponse(WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.Respuesta EnviarCorreoResult;
        
        public EnviarCorreoResponseBody() {
        }
        
        public EnviarCorreoResponseBody(WebApiLatinAmericaJourneys.ws_SendGridEmail.Respuesta EnviarCorreoResult) {
            this.EnviarCorreoResult = EnviarCorreoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsMailsSoapChannel : WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsMailsSoapClient : System.ServiceModel.ClientBase<WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap>, WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap {
        
        public wsMailsSoapClient() {
        }
        
        public wsMailsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsMailsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsMailsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsMailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponse WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap.EnviarCorreo(WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreo(request);
        }
        
        public WebApiLatinAmericaJourneys.ws_SendGridEmail.Respuesta EnviarCorreo(WebApiLatinAmericaJourneys.ws_SendGridEmail.Autenticacion credenciales, WebApiLatinAmericaJourneys.ws_SendGridEmail.Correo informacion) {
            WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest inValue = new WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest();
            inValue.Body = new WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequestBody();
            inValue.Body.credenciales = credenciales;
            inValue.Body.informacion = informacion;
            WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponse retVal = ((WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap)(this)).EnviarCorreo(inValue);
            return retVal.Body.EnviarCorreoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponse> WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap.EnviarCorreoAsync(WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoResponse> EnviarCorreoAsync(WebApiLatinAmericaJourneys.ws_SendGridEmail.Autenticacion credenciales, WebApiLatinAmericaJourneys.ws_SendGridEmail.Correo informacion) {
            WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest inValue = new WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequest();
            inValue.Body = new WebApiLatinAmericaJourneys.ws_SendGridEmail.EnviarCorreoRequestBody();
            inValue.Body.credenciales = credenciales;
            inValue.Body.informacion = informacion;
            return ((WebApiLatinAmericaJourneys.ws_SendGridEmail.wsMailsSoap)(this)).EnviarCorreoAsync(inValue);
        }
    }
}
